name: Deploy MkDocs Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material \
                      mkdocstrings[python] \
                      mkdocs-minify-plugin \
                      mkdocs-git-revision-date-localized-plugin
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
