name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: pip install uv build
p
      - name: Build the package
        run: uv build

      # Test PyPI
      - name: Publish to TestPyPI
        id: testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # PyPI
      - name: Publish to PyPI
        if: steps.testpypi.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1